### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by dhruv866** [ManakhovN/FigmaToUnityImporter#12]
I am importing the package by add git url but it showing error. Please Help
![Screenshot (5)](https://user-images.githubusercontent.com/64523762/122673139-c3a83580-d1ec-11eb-9f89-1a3ec88cbf9b.png)

**Comment by ManakhovN** [comment]
Hello! I've tried to install it. And it works for me. Please be sure that you put the proper git URL in the upm. It must be: https://github.com/ManakhovN/FigmaToUnityImporter.git?path=/Assets/FigmaImporter

**Comment by dhruv866** [comment]
Still not working

**Comment by ManakhovN** [comment]
> Still not working

Could you possibly write the exact steps that leads to this error?

**Comment by dhruv866** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/64523762/122682131-4e9d2600-d215-11eb-8454-bc43b210e5f9.png)
![Screenshot (7)](https://user-images.githubusercontent.com/64523762/122682134-50ff8000-d215-11eb-9d86-f3f940fb6827.png)

**Comment by ManakhovN** [comment]
Which version of unity do u use?

**Comment by dhruv866** [comment]
Unity 2021.1.7f1

**Comment by ManakhovN** [comment]
> Unity 2021.1.7f1

I tried it on this version and it works. I still think that you put the wrong git URL. Why it is so long on your first screen in the error? Can you write the full line that u put there? I don't see the whole link from your screen.

**Comment by MSharamok** [comment]
Instal [git](https://git-scm.com/) and reload unity and unity hub
