### ISSUE TITLE
Scaling option

### ISSUE THREAD

**Issue by SolidAlloy** [ManakhovN/FigmaToUnityImporter#13]
Due to technical reasons, designers on our team create UI in one resolution, but the canvas in Unity is three times larger, so we export all PNGs with 3x scale, and multiply all distances between elements by 3. Would it be possible/difficult to implement the scaling option when generating nodes?

**Comment by ManakhovN** [comment]
I think yes. It is possible to implement the scale option there. You will need to multiply size and positions to this number. If you want to get scaled renders of the nodes you can do it via Figma API, as I remember.
I don't think that I am going to implement this feature soon. So you can try to do it.

**Comment by SolidAlloy** [comment]
Wow, thank you, I'll try it! Didn't expect that you actually implement it, thanks again :smile:
