### ISSUE TITLE
Broken plug-in.

### ISSUE THREAD

**Issue by maskedvillain** [ManakhovN/FigmaToUnityImporter#25]
Just ran this with a super simple Figma project. Like two frames and nothing imports. The node import doesn’t return anything at all.

**Comment by ManakhovN** [comment]
Hello. Did u follow all the steps of how to use it? Probably the auth token is not right, so the frames are not loaded. Anyway, I can't say what is wrong without full description of your steps to reproduce the problem. Please write it, so I could help you.

**Comment by fitzeekdrew** [comment]
The frames all get fetched and load into the list of the editor (right panel), they just don’t show anything in unity scene setup (left panel). All just a bunch of empty objects
  
  
  
    
  

  
  
>

**Comment by fitzeekdrew** [comment]
Exactly. Just paid for this!
  
  
  
  
  
  
  

  
  
>

**Comment by ManakhovN** [comment]
@fitzeekdrew I am sorry, but the plugin is absolutely free. What do u mean by saying that u paid for it?
@fitzeekdrew @jmozunes could you possibly share a problematic project at least? Otherwise It is hard to guess what is wrong there.

**Comment by jmozunes** [comment]
Hi @ManakhovN , I think the issue is the URL, it cannot import multiple frames at a time. But I manage to import it one by one.

**Comment by jmozunes** [comment]
![URL01](https://user-images.githubusercontent.com/101314257/158047742-4dd1208d-6879-404f-80be-82ef776f9356.JPG)

This is the URL if I selected multiple frames, and it will show Null reference exception just what is shown here,. https://user-images.githubusercontent.com/101314257/157914150-ce700fc0-a22b-4709-8ec5-6fdc3e13d575.JPG

**Comment by jmozunes** [comment]
Just need to select each frame, and import it one by one...
![URL02](https://user-images.githubusercontent.com/101314257/158047778-166f4d85-3ec8-42fa-ae67-3dd5512d191b.JPG)
![URL03](https://user-images.githubusercontent.com/101314257/158047779-903da104-5993-420f-852a-6b1a0a54bbda.JPG)

**Comment by jmozunes** [comment]
For now it works well for me. I am just looking forward, for also buttons and other UI components will be available to import in Unity.

**Comment by ManakhovN** [comment]
@jmozunes Yes, the plugin doesn't support multiple frames importing. For now, you have to import them one by one.

**Comment by fitzeekdrew** [comment]
I’m confused. All Figma projects are made up of multiple frames.   Are you referring to recursive frames (nested) or basically artboards?
  
  
  
  
  
  
  

  
  
>

**Comment by fitzeekdrew** [comment]
Okay. What DOES work? Don’t really understand the point of this
  
  
  
  
  
  
  

  
  
>

**Comment by ManakhovN** [comment]
@fitzeekdrew I dont understand what do u want from me. Firstly, you haven't provided any screenshots/projects that can explain what is wrong. Secondly, you wrote that you paid for this. What? I don't sell this tool, it is open source and can be used however you want. I dont get money from you than I owe you nothing. 
Like it was written before it supports importing a single frame. If you have a case when it doesn't work just fully describe your problem and attach link to your project. Or you can become a contributor and push a code that will fix it.

https://user-images.githubusercontent.com/7031314/161379478-92972b48-e9fa-435a-85a8-c1259c479f13.mp4

**Comment by VladislavMm** [comment]
In the new version of figma, the link has a problem, for example, in the link node-id is written as 0-1, and you need 0:1 for the IP, nothing may work for this, try just changing the node-id in the link that you insert, replace "-" with ":"

**Comment by ManakhovN** [comment]
> In the new version of figma, the link has a problem, for example, in the link node-id is written as 0-1, and you need 0:1 for the IP, nothing may work for this, try just changing the node-id in the link that you insert, replace "-" with ":" ![image](https://user-images.githubusercontent.com/53298335/223749838-441c7061-f71f-41d8-843a-e1a33afdba27.png) ![image](https://user-images.githubusercontent.com/53298335/223749952-a47205b6-5b5c-49c6-8d74-c67dc19086d1.png)

Thank you for warning. Did they change it recently?

**Comment by VladislavMm** [comment]
> Thank you for warning. Did they change it recently?
Yes, this month
