### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by flash1o** [ManakhovN/FigmaToUnityImporter#27]
I think they changed something in their API, so I cant use the importer anymore.
![Снимок экрана 2023-05-11 192956](https://github.com/ManakhovN/FigmaToUnityImporter/assets/74831919/a030d40d-dd0f-4df4-9fde-5f3fa0be738b)

**Comment by ManakhovN** [comment]
@flash1o Thanks for warning. I will take a look.

**Comment by VladislavMm** [comment]
> I think they changed something in their API, so I cant use the importer anymore. ![Снимок экрана 2023-05-11 192956](https://user-images.githubusercontent.com/74831919/237768206-a030d40d-dd0f-4df4-9fde-5f3fa0be738b.jpg)

Well, this is of course very little data) The error is that he is trying to go beyond the boundaries of the array, show what you have here 
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/53298335/f409e6b2-3244-486c-8666-3d7e2f95e2ef)
Open the script and put there such a Debug.log show what it gives. Put a stop point (if you know how). Everything works for me, but I have the code changed for myself, it's hard to determine) The more data you give, the faster the problem will be solved)

**Comment by VladislavMm** [comment]
And I found a jamb in the code on the git, yes figma changed the link and now it's at the beginning 
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/53298335/15afaee0-7926-4b55-9c63-f4d2cdf36b9e)
And before it was like this 
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/53298335/83b237a5-6f19-49d7-91d2-dcc68d13ddb8)
My code looks like this, so there was no error -
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/53298335/d43aff68-299d-4c76-ae0f-a764725068ea)

**Comment by ManakhovN** [comment]
@VladislavMm Thank you for spotting the problem and for the solution. I pushed it to the main branch. Next time dont be shy to make a PR with fix.
