### ISSUE TITLE
FigmaNodeGenerator -> AddFills -> NullReferenceException

### ISSUE THREAD

**Issue by Smirnov-Mikhail** [ManakhovN/FigmaToUnityImporter#32]
Hello!
We have _fill.type_ "GRADIENT_LINEAR" for TextMeshProUGUI

I'm not sure how it should work, but I made the hack (on the screenshot) and it doesn't throw exception now and looks similar (but not the same)

![FigmaNodeGeneratorNullRef](https://github.com/ManakhovN/FigmaToUnityImporter/assets/6568161/b610d9e4-c579-4d98-ab58-da390446f6d4)

**Comment by Smirnov-Mikhail** [comment]
I think I can't link issue and PR, but anyway I created it: https://github.com/ManakhovN/FigmaToUnityImporter/pull/34

**Comment by ManakhovN** [comment]
@Smirnov-Mikhail Thank you very much! Accepted the PR
