### ISSUE TITLE
Namespace Error

### ISSUE THREAD

**Issue by altayturan** [ManakhovN/FigmaToUnityImporter#33]
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/69851770/8958b5f1-695c-469f-ba68-49bac1c40cc7)
![image](https://github.com/ManakhovN/FigmaToUnityImporter/assets/69851770/56a2e08e-a46a-44f9-91de-321498b72bb3)

There is namespace errors. How can I fix that?

**Comment by ManakhovN** [comment]
@altayturan What is the version of the Unity you use? I just recently tried to add package, everything works fine. How are you trying to install it?
Try to delete package-lock.json file in Packages folder.

**Comment by ManakhovN** [comment]
Closing because of no response from the issue starter.
