### ISSUE TITLE
About unity version[Question]

### ISSUE THREAD

**Issue by ayutaz** [ManakhovN/FigmaToUnityImporter#5]
It seems that the Unity version you are using is a little older than 2019.3.0f6.
We are thinking of upgrading to 2019.4.26f1 or 2020.3.8f1 so that more people can use it.
Is there anything that can only be done with 2019.3.0f6?
I would also like to be able to support UPM so that more people can use it.

I would like to hear your opinion.
Thank you very much.

Addendum::
Thank you for the quick merge of the PullRequest!

**Comment by ManakhovN** [comment]
There is no version-dependent code. So it must work on a later version of Unity without any problems, I checked it in 2020.2.0f1. But you better check it on your unity version, before using it on a real project.
Adding UPM support in plans.

**Comment by ayutaz** [comment]
Thank you for your answer.
So, I'm thinking of upgrading the version of Unity in this project to LTS support, what do you think? (I'd like to publish the updated version as PR).

I would also like to release a PR with additional UPM.

**Comment by ManakhovN** [comment]
Hello. Actually, the version of Unity doesn't matter, but if you think it would be better to upgrade the project to the LTS version, why not. And u can add supporting UPM, I will be thankful.
I have seen u just closed your PR, what is wrong with it?

**Comment by ayutaz** [comment]
I also think that the version of unity is not very important. However, I upgraded it just in case (PR #6 ).

The reason why I closed the PR is because I found out that the UPM support is not complete yet. I'd like to submit another PR to fix it.
